### ISSUE TITLE
Tmdb helper

### ISSUE THREAD

**Issue by Basti83x** [michaz1988/repo#15]
Hi. habe probiert mit tmdb helper ein player für vavoo zu erstellen aber es geht irgendwie nicht. Er lässt sich zwar erstellen aber: 
Die suche wird gestartet es wird was gefunden dann dreht sich sofort wieder der kreis und das suchfenster geht wieder auf. Nur dieses mal ist es leer. Könntest du vielleicht mal schauen woran das liegt oder vielleicht ein player für tmdb helper erstellen?  Qürde vavoo wirklich gerne mit dem tmsb helper addon nutzen. Schon mal danke im vorraus...

**Comment by michaz1988** [comment]
https://github.com/michaz1988/michaz1988.github.io/raw/master/players.zip

kann man direkt im TMDB-HELPER eingeben :![Screenshot_2023-06-03-07-49-17-062_org.xbmc.kodi-edit.jpg](https://github.com/michaz1988/repo/assets/45913369/55d4fe8d-767b-4ae1-b08c-c60c4c61ebda)

**Comment by Basti83x** [comment]
Siper Dankeschön. Funktioniert perfekt 👍

**Comment by urs45** [comment]
funktioniert nur für Filme, bei Serien immer Fehlermeldung dass keine Quellen vorhanden. Manuell bei Vavoo aber vorhanden und läuft nur eben der Tmdbh player funktioniert nicht. Schade.
